apiVersion: apps/v1
kind: Deployment
metadata:
  name: devquote-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devquote
  template:
    metadata:
      labels:
        app: devquote
    spec:
      containers:
      - name: devquote
        image: harshtripathi02/devquote-api:latest
        ports:
        - containerPort: 3000
